// Generates the industry landing pages from the PAGES data below.
// Header, process, contact form and footer are copied from index.html so they stay in sync.
// Run after editing index.html or this file:   node tools/build-pages.js
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://samverse.space';
const WA = '917417049145';
const index = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const between = (start, end) => {
  const a = index.indexOf(start);
  const b = index.indexOf(end, a);
  if (a < 0 || b < 0) throw new Error(`Section not found in index.html: ${start}`);
  return index.slice(a, b + end.length);
};
// Make copied markup work from a sub-folder, and point site nav at the homepage sections
const rebase = html => html
  .replace(/(src|href)="assets\//g, '$1="/assets/')
  .replace(/href="#(about|services|work|process|faq|industries)"/g, 'href="/#$1"')
  .replace(/href="#top" class="brand"/g, 'href="/" class="brand"');

const header = rebase(between('<header class="header"', '</header>'));
const process_ = between('<!-- ===== Process ===== -->', '</section>');
const contact = between('<!-- ===== Contact ===== -->', '</section>');
const footer = rebase(between('<footer class="footer">', '</footer>'));
const waFloat = between('<a class="wa-float"', '</a>');

const PAGES = require('./pages-data');

const tick = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 16.2l-3.5-3.5L4 14.2l5 5 11-11-1.4-1.4z"/></svg>';

const related = p => {
  const same = PAGES.filter(x => x.type === p.type);
  const i = same.indexOf(p);
  return [1, 2, 3].map(n => same[(i + n) % same.length]).filter(x => x !== p);
};
const card = x => `<a class="industry" href="/${x.slug}/"><h3>${esc(x.nav)}</h3><p>${esc(x.description.split('. ')[0])}.</p><span class="ind-arrow">→</span></a>`;

const render = p => {
  const url = `${SITE}/${p.slug}/`;
  const waLink = `https://wa.me/${WA}?text=${encodeURIComponent(p.wa)}`;
  const plainH1 = p.h1.replace(/<[^>]+>/g, '');
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Service', '@id': `${url}#service`, name: plainH1, serviceType: p.nav, description: p.description, url,
        areaServed: 'Worldwide',
        provider: { '@type': 'Person', '@id': `${SITE}/#sameer`, name: 'Sameer Gupta', url: `${SITE}/`, telephone: '+91-7417049145' },
      },
      {
        '@type': 'BreadcrumbList', itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: p.nav, item: url },
        ],
      },
      {
        '@type': 'FAQPage', mainEntity: p.faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })),
      },
    ],
  };

  return `<!DOCTYPE html>
<html lang="en-IN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(p.title)}</title>
  <meta name="description" content="${esc(p.description)}">
  <meta name="author" content="Sameer Gupta">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Samverse">
  <meta property="og:locale" content="en_IN">
  <meta property="og:url" content="${url}">
  <meta property="og:title" content="${esc(p.title)}">
  <meta property="og:description" content="${esc(p.description)}">
  <meta property="og:image" content="${SITE}/assets/og-image.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:image" content="${SITE}/assets/og-image.png">
  <meta name="theme-color" content="#6D4AFF">
  <link rel="icon" type="image/svg+xml" href="/assets/logo-mark.svg">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32.png">
  <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <script src="/config.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/style.css">
  <script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
  </script>
</head>
<body>

  <!-- Generated by tools/build-pages.js: edit that file, not this one -->
  ${header}

  <main>
    <section class="hero lp-hero">
      <div class="container">
        <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> <span>/</span> ${esc(p.nav)}</nav>
        <div class="lp-hero-copy reveal">
          <span class="pill"><span class="dot"></span> ${esc(p.eyebrow)}</span>
          <h1>${p.h1}</h1>
          <p class="lead">${esc(p.lead)}</p>
          <div class="hero-cta">
            <a href="#contact" class="btn">Get a Free Quote</a>
            <a href="${waLink}" class="btn btn-ghost" target="_blank" rel="noopener">WhatsApp Me</a>
          </div>
          <ul class="lp-trust">
            <li>${tick} Building WordPress sites since 2020</li>
            <li>${tick} Fixed quote in 24 hours</li>
            <li>${tick} Support after launch</li>
          </ul>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <div class="section-head reveal">
          <span class="eyebrow">Why it matters</span>
          <h2>${esc(p.painTitle)}</h2>
        </div>
        <div class="services-grid lp-benefits">
${p.pains.map(([t, d]) => `          <article class="service reveal"><div class="icon">${tick}</div><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('\n')}
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container lp-gets reveal">
        <div>
          <span class="eyebrow">What you get</span>
          <h2>${esc(p.getsTitle)}</h2>
          <p class="muted">Every project is built on WordPress, so you own your website and can update it yourself. Need something that isn't listed? Just ask.</p>
          <a href="#contact" class="btn" style="margin-top:22px">Discuss Your Project</a>
        </div>
        <ul class="checklist">
${p.gets.map(g => `          <li>${tick} ${esc(g)}</li>`).join('\n')}
        </ul>
      </div>
    </section>

    <section class="section" id="work">
      <div class="container">
        <div class="section-head reveal">
          <span class="eyebrow">Related work</span>
          <h2>Websites I've built</h2>
          <p class="muted">Live projects. Click a card to visit the site, or <a href="/#work" class="link-inline">see the full portfolio</a>.</p>
        </div>
        <div class="work-grid" id="workGrid" data-projects="${esc(p.projects.join('|'))}"></div>
      </div>
    </section>

    ${process_}

    <section class="section" id="faq">
      <div class="container faq-wrap">
        <div class="section-head reveal">
          <span class="eyebrow">FAQ</span>
          <h2>Common questions</h2>
        </div>
        <div class="faq reveal">
${p.faqs.map(([q, a]) => `          <details>\n            <summary>${esc(q)}</summary>\n            <p>${esc(a)}</p>\n          </details>`).join('\n')}
        </div>
      </div>
    </section>

    <section class="section related">
      <div class="container">
        <div class="section-head reveal">
          <span class="eyebrow">${p.type === 'industry' ? 'Other industries' : 'Related services'}</span>
          <h2>You might also need</h2>
        </div>
        <div class="industries related-grid reveal">
${related(p).map(x => '          ' + card(x)).join('\n')}
        </div>
        <p class="related-all"><a href="/solutions/" class="link-inline">See all industries &amp; services →</a></p>
      </div>
    </section>

    ${contact}
  </main>

  ${footer}

  ${waFloat.replace(/href="[^"]*"/, `href="${waLink}"`)}

  <script src="/script.js" defer></script>
</body>
</html>
`;
};

for (const p of PAGES) {
  const dir = path.join(ROOT, p.slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), render(p));
  console.log('built', `/${p.slug}/`);
}

// /solutions/ hub: links to every landing page (helps Google discover them all)
const hub = () => {
  const group = (type, title, intro) => `
    <section class="section">
      <div class="container">
        <div class="section-head reveal">
          <span class="eyebrow">${type === 'industry' ? 'Industries' : 'Services'}</span>
          <h2>${title}</h2>
          <p class="muted">${intro}</p>
        </div>
        <div class="industries reveal">
${PAGES.filter(x => x.type === type).map(x => '          ' + card(x)).join('\n')}
        </div>
      </div>
    </section>`;
  const url = `${SITE}/solutions/`;
  const schema = {
    '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'WordPress Services & Industries', url,
    hasPart: PAGES.map(x => ({ '@type': 'WebPage', name: x.nav, url: `${SITE}/${x.slug}/` })),
  };
  return `<!DOCTYPE html>
<html lang="en-IN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WordPress Services &amp; Industries | Samverse by Sameer Gupta</title>
  <meta name="description" content="All WordPress services by Sameer Gupta: website design for doctors, manufacturers, restaurants, real estate and more, plus redesign, speed, SEO, maintenance and security.">
  <meta name="robots" content="index, follow">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:title" content="WordPress Services & Industries | Samverse">
  <meta property="og:image" content="${SITE}/assets/og-image.png">
  <meta name="theme-color" content="#6D4AFF">
  <link rel="icon" type="image/svg+xml" href="/assets/logo-mark.svg">
  <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
  <script src="/config.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/style.css">
  <script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
  </script>
</head>
<body>

  <!-- Generated by tools/build-pages.js -->
  ${header}

  <main>
    <section class="hero lp-hero">
      <div class="container">
        <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> <span>/</span> Solutions</nav>
        <div class="lp-hero-copy reveal">
          <h1>WordPress solutions for <span class="grad">every kind of business</span></h1>
          <p class="lead">Pick your industry or the service you need to see exactly how I can help. Not sure? Send me a message and I'll recommend the right approach.</p>
          <div class="hero-cta">
            <a href="#contact" class="btn">Get a Free Quote</a>
            <a href="https://wa.me/${WA}" class="btn btn-ghost" target="_blank" rel="noopener">WhatsApp Me</a>
          </div>
        </div>
      </div>
    </section>
${group('industry', 'Websites by industry', 'Websites planned around what your customers need to see and do.')}
${group('service', 'Services', 'Specialist WordPress services for new and existing websites.')}

    ${contact}
  </main>

  ${footer}

  ${waFloat}

  <script src="/script.js" defer></script>
</body>
</html>
`;
};
fs.mkdirSync(path.join(ROOT, 'solutions'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'solutions', 'index.html'), hub());
console.log('built /solutions/');

// Keep the sitemap in step with the pages
const today = new Date().toISOString().slice(0, 10);
const urls = [{ loc: `${SITE}/`, pr: '1.0' }, { loc: `${SITE}/solutions/`, pr: '0.9' }, ...PAGES.map(p => ({ loc: `${SITE}/${p.slug}/`, pr: '0.8' }))];
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${u.pr}</priority>\n  </url>`).join('\n')}
</urlset>
`);
console.log('updated sitemap.xml');

module.exports = { PAGES };
