// Content for every landing page. Add a page by adding an entry, then run: node tools/build-pages.js
// type: 'industry' or 'service' (used to group pages on /solutions/)
const PAGES = [
  // ===================== INDUSTRIES =====================
  {
    type: 'industry',
    slug: 'wordpress-developer-for-agencies',
    nav: 'For Agencies',
    title: 'White-Label WordPress Developer for Agencies | Samverse',
    description: 'Outsource WordPress and Elementor development to a reliable white-label developer in India. Your brand, your client relationship, fixed quotes and on-time delivery.',
    eyebrow: 'For digital & design agencies',
    h1: 'Your <span class="grad">white-label</span> WordPress developer',
    lead: 'You win the client, I build the website. I turn your agency\'s designs and briefs into fast, responsive WordPress sites under your brand, so you can take on more projects without hiring.',
    wa: 'Hi Sameer, I run an agency and want to discuss white-label WordPress work.',
    painTitle: 'Why agencies outsource to me',
    pains: [
      ['Your name, not mine', 'I work behind the scenes under NDA. No contact with your clients unless you want it, and no credits on the site.'],
      ['Design to WordPress, accurately', 'Figma, XD or PDF designs built pixel-accurately in Elementor or your preferred theme.'],
      ['Clear, fixed quotes', 'A fixed price per project before work starts, so you can quote your client with confidence and keep your margin.'],
      ['Handles the overflow', 'Take on extra projects in busy months without hiring or training a full-time developer.'],
    ],
    getsTitle: 'What I can take off your plate',
    gets: ['Business & corporate websites', 'Landing pages for ad campaigns', 'WooCommerce stores', 'Theme & Elementor customization', 'Speed optimization & Core Web Vitals', 'Site migrations & redesigns', 'Monthly maintenance for your clients', 'Bug fixes & urgent updates'],
    projects: ['Third Eye Social', 'Streak Creative', 'Vansh Group', 'India Automation Hub'],
    faqs: [
      ['Do you work under NDA?', 'Yes. I\'m happy to sign an NDA, and I never contact your clients directly or add my credit to the sites I build for you.'],
      ['How do you price agency work?', 'Each project gets a fixed quote based on the pages and features in your brief. Regular partners get priority scheduling.'],
      ['What do you need from us to start?', 'The design files or reference sites, the content (or a note on who provides it), and hosting or staging access. I\'ll confirm scope and timeline before starting.'],
      ['Can you handle ongoing maintenance for our clients?', 'Yes. I can manage updates, backups, security checks and small changes on a monthly basis for your client sites.'],
    ],
  },
  {
    type: 'industry',
    slug: 'wordpress-website-for-doctors',
    nav: 'Doctors & Clinics',
    title: 'Website Design for Doctors & Clinics in India | WordPress | Samverse',
    description: 'Professional WordPress websites for doctors, clinics and hospitals. Mobile-friendly, fast, found on Google, with appointment enquiries straight to WhatsApp.',
    eyebrow: 'For doctors, clinics & hospitals',
    h1: 'Websites that help <span class="grad">patients find you</span> and book',
    lead: 'Patients search on Google before they choose a doctor. I build professional, mobile-friendly clinic websites that build trust, rank for local searches and turn visitors into appointment enquiries.',
    wa: 'Hi Sameer, I need a website for my clinic / practice.',
    painTitle: 'What a good clinic website does for you',
    pains: [
      ['Builds trust before the visit', 'Your qualifications, experience, treatments and clinic photos presented professionally, so patients choose you with confidence.'],
      ['Gets found in local search', 'SEO set up for searches like "dermatologist near me" or "best orthopaedic doctor in [city]", along with your Google Business Profile.'],
      ['Makes booking easy', 'One-tap call, WhatsApp and appointment enquiry forms that work perfectly on the phones your patients use.'],
      ['Easy for your staff to update', 'Timings, notices and new treatments can be updated without calling a developer.'],
    ],
    getsTitle: 'What your clinic website includes',
    gets: ['Doctor profile & qualifications', 'Treatments & services pages', 'Appointment enquiry form', 'WhatsApp & one-tap call buttons', 'Google Maps & clinic timings', 'Patient testimonials section', 'Local SEO setup', 'Fast, mobile-first design'],
    projects: ['Dr. Sunaina Dental Care', 'Dr. Sudhir Arora'],
    faqs: [
      ['Can patients book appointments on the website?', 'Yes. I can add an appointment enquiry form that emails you and opens WhatsApp, or integrate a booking system if you use one.'],
      ['Will my clinic show up on Google?', 'I set up on-page SEO, schema markup for medical practices, a sitemap and Search Console, and help link your Google Business Profile. That gives you the right foundation for local searches.'],
      ['How long does a clinic website take?', 'Usually 1–2 weeks once I have your content: photos, qualifications and the list of treatments.'],
      ['Can you write the content for the site?', 'I can structure the pages and help polish your content. Medical details should come from you so they are accurate.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-manufacturers',
    nav: 'Manufacturers & B2B',
    title: 'Website Design for Manufacturers & Industrial Companies | Samverse',
    description: 'WordPress websites for manufacturers, industrial suppliers and B2B companies. Product catalogues, enquiry forms and SEO that bring in bulk and export enquiries.',
    eyebrow: 'For manufacturers, industrial & B2B',
    h1: 'B2B websites that <span class="grad">bring in enquiries</span>',
    lead: 'Buyers and procurement teams check your website before they call. I build clear, professional websites for manufacturers and industrial suppliers that show your products and capability, and turn visits into RFQs.',
    wa: 'Hi Sameer, I need a website for my manufacturing / B2B company.',
    painTitle: 'What your B2B website should do',
    pains: [
      ['Show your capability', 'Products, certifications, facilities and clients presented so buyers take you seriously from the first visit.'],
      ['Organise large catalogues', 'Product categories, specifications and downloadable brochures that are easy to browse and easy for you to update.'],
      ['Capture enquiries', 'Quote-request forms on every product, plus WhatsApp and email, so no enquiry is lost.'],
      ['Found by the right buyers', 'SEO for your product and industry keywords, so buyers searching for what you make can find you.'],
    ],
    getsTitle: 'What your company website includes',
    gets: ['Company profile & infrastructure', 'Product catalogue with specifications', 'Request-a-quote forms', 'Brochure & datasheet downloads', 'Certifications & client logos', 'Industries served pages', 'SEO for product keywords', 'Fast, mobile-friendly design'],
    projects: ['India Automation Hub', 'Sahni Power Solutions', 'Vansh Group'],
    faqs: [
      ['Can I add and update products myself?', 'Yes. Products are managed from the WordPress dashboard, so you can add items, change specifications and upload brochures without code.'],
      ['Do you build catalogues without online payments?', 'Yes. Most B2B sites use a catalogue with "Request a Quote" instead of a cart, and I can set up either.'],
      ['Can the website support export enquiries?', 'Yes. I can structure the site for international buyers and add multilingual support if you need it.'],
      ['How long does a B2B website take?', 'Usually 2–3 weeks depending on the number of products and pages, once content is ready.'],
    ],
  },
  {
    type: 'service',
    slug: 'woocommerce-developer',
    nav: 'Online Stores',
    title: 'WooCommerce Developer in India | Online Store Setup | Samverse',
    description: 'Hire a WooCommerce developer to build your online store on WordPress: products, payment gateways like Razorpay, shipping, and a fast mobile checkout.',
    eyebrow: 'For brands & online stores',
    h1: 'Start selling online with a <span class="grad">WooCommerce</span> store',
    lead: 'Own your online store instead of paying marketplace commissions. I build fast, mobile-friendly WooCommerce stores with payments, shipping and everything set up so you can start taking orders.',
    wa: 'Hi Sameer, I want to build an online store with WooCommerce.',
    painTitle: 'Why brands choose WooCommerce with me',
    pains: [
      ['No marketplace commission', 'Sell directly to customers on your own website and keep more of every order.'],
      ['Payments & shipping ready', 'Indian payment gateways like Razorpay, PayU or Cashfree, COD options and shipping rules set up and tested.'],
      ['Fast mobile checkout', 'Most shoppers buy on their phone, so product pages and checkout are optimized for speed and ease.'],
      ['Easy to manage', 'Add products, manage stock and process orders yourself from a simple dashboard.'],
    ],
    getsTitle: 'What your store includes',
    gets: ['Product catalogue & categories', 'Payment gateway integration', 'Cash on Delivery & shipping rules', 'Order & stock management', 'Order email notifications', 'Coupons & discounts', 'WhatsApp chat button', 'Speed & SEO optimization'],
    projects: ['CNN Food & Spices'],
    faqs: [
      ['Which payment gateways can you set up?', 'Popular Indian gateways such as Razorpay, PayU, Cashfree and PhonePe, plus PayPal or Stripe for international payments, and Cash on Delivery.'],
      ['How many products can the store have?', 'WooCommerce handles anything from a few products to thousands. I can also import your existing product list from a spreadsheet.'],
      ['Can I manage orders on my phone?', 'Yes. You can manage orders from the WordPress dashboard in your browser or the WooCommerce mobile app.'],
      ['How long does a store take to build?', 'Usually 2–4 weeks, depending on the number of products and features, once product details and photos are ready.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-restaurants',
    nav: 'Restaurants & Cafes',
    title: 'Restaurant & Cafe Website Design | WordPress | Samverse',
    description: 'Mouth-watering WordPress websites for restaurants, cafes, bakeries and food brands, with menus, table reservations, online ordering and Google Maps.',
    eyebrow: 'For restaurants, cafes & food brands',
    h1: 'Restaurant websites that <span class="grad">fill tables</span>',
    lead: 'Hungry customers check your menu, photos and timings online before they visit or order. I build fast, beautiful restaurant websites that make them want to come in, book a table or order directly.',
    wa: 'Hi Sameer, I need a website for my restaurant / cafe.',
    painTitle: 'What your restaurant website should do',
    pains: [
      ['Show off your food', 'Big, fast-loading photo galleries and a menu that looks great on phones, not a blurry PDF.'],
      ['Take bookings and orders', 'Table reservation forms, WhatsApp ordering or a full online ordering system, so you keep the commission aggregators charge.'],
      ['Get found nearby', 'Local SEO and Google Maps integration for searches like "best cafe near me".'],
      ['Update in minutes', 'Change dishes, prices and daily specials yourself, with no developer needed.'],
    ],
    getsTitle: 'What your restaurant website includes',
    gets: ['Mobile-friendly digital menu', 'Table reservation form', 'WhatsApp / online ordering', 'Photo gallery', 'Google Maps & opening hours', 'Instagram feed', 'Reviews & testimonials', 'Local SEO setup'],
    projects: ['CNN Food & Spices'],
    faqs: [
      ['Can customers order food directly from my website?', 'Yes. I can set up WhatsApp ordering for simple needs, or a full WooCommerce ordering system with online payments and delivery areas.'],
      ['Can I update the menu myself?', 'Yes. The menu is managed from the WordPress dashboard, so you can add dishes, change prices or mark items unavailable anytime.'],
      ['Can you add QR code menus for tables?', 'Yes. Your online menu page can be linked to a QR code for contactless table menus.'],
      ['How long does a restaurant website take?', 'Usually 1–2 weeks once I have your menu, photos and logo.'],
    ],
  },
  {
    type: 'industry',
    slug: 'real-estate-website-design',
    nav: 'Real Estate & Builders',
    title: 'Real Estate Website Design for Builders & Agents | Samverse',
    description: 'WordPress websites for real estate builders, developers and property agents, with project pages, property listings, floor plans and lead capture forms.',
    eyebrow: 'For builders, developers & property agents',
    h1: 'Real estate websites that <span class="grad">generate site visits</span>',
    lead: 'Property buyers research online long before they call. I build professional real estate websites that showcase your projects, build credibility and capture enquiries from serious buyers.',
    wa: 'Hi Sameer, I need a real estate website.',
    painTitle: 'What a real estate website needs to do',
    pains: [
      ['Showcase every project', 'Dedicated project pages with galleries, floor plans, amenities, location maps and RERA details.'],
      ['Capture serious buyers', 'Enquiry and site-visit forms, brochure downloads and WhatsApp on every page, so leads come straight to you.'],
      ['Built for ad campaigns', 'Fast landing pages for Google and Facebook ads that turn ad clicks into leads, not bounces.'],
      ['Build trust', 'Completed projects, approvals and testimonials presented clearly to reassure buyers.'],
    ],
    getsTitle: 'What your real estate website includes',
    gets: ['Project & property pages', 'Floor plans & price lists', 'Photo & video galleries', 'Site-visit booking form', 'Brochure download with lead capture', 'Location maps & nearby places', 'RERA & approvals section', 'Landing pages for ads'],
    projects: ['Vansh Group', 'India Automation Hub', 'Sahni Power Solutions'],
    faqs: [
      ['Can I add property listings myself?', 'Yes. Projects and listings are managed from the dashboard. You can add photos, prices and status (available, sold) anytime.'],
      ['Can buyers download a brochure after entering their details?', 'Yes. I can set up gated brochure downloads so you capture the name and phone number of every interested buyer.'],
      ['Do you make landing pages for property ads?', 'Yes. I build fast, focused landing pages for each project that work well with Google Ads and Meta ads.'],
      ['Can the site show multiple projects and locations?', 'Yes. The site can be organised by project, city, status (ongoing, completed) or property type.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-schools-and-coaching',
    nav: 'Schools & Coaching',
    title: 'Website Design for Schools, Colleges & Coaching Institutes | Samverse',
    description: 'WordPress websites for schools, colleges, coaching centres and tutors, with admissions enquiries, courses, results, galleries and notice boards.',
    eyebrow: 'For schools, colleges & coaching institutes',
    h1: 'Education websites that <span class="grad">boost admissions</span>',
    lead: 'Parents and students compare institutes online before they enquire. I build clear, trustworthy education websites that highlight your results, faculty and courses, and make admission enquiries easy.',
    wa: 'Hi Sameer, I need a website for my school / coaching institute.',
    painTitle: 'What your institute website should do',
    pains: [
      ['Win parents\' trust', 'Results, toppers, faculty profiles, facilities and achievements presented professionally.'],
      ['Drive admission enquiries', 'Admission forms, course enquiry buttons and WhatsApp that work perfectly on mobile.'],
      ['Keep everyone informed', 'Notice board, events, holidays and announcements you can update in minutes.'],
      ['Rank in local search', 'SEO for searches like "best coaching for NEET in {city}" so students find you.'],
    ],
    getsTitle: 'What your education website includes',
    gets: ['Courses & batches pages', 'Admission enquiry form', 'Results & toppers section', 'Faculty profiles', 'Notice board & events', 'Photo & video gallery', 'Downloadable prospectus', 'Local SEO setup'],
    projects: ['Our Temples', 'Dr. Sudhir Arora', 'Vansh Group'],
    faqs: [
      ['Can we post notices and results ourselves?', 'Yes. Staff can post notices, events and results from the dashboard without any technical knowledge.'],
      ['Can students apply or enquire online?', 'Yes. I set up admission and course enquiry forms that email you instantly, with WhatsApp follow-up.'],
      ['Can you add online fee payment?', 'Yes. I can integrate a payment gateway such as Razorpay so fees can be paid online.'],
      ['Can the site support online classes or course sales?', 'Yes. WordPress LMS plugins can handle video courses, quizzes and paid enrolments if you need them.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-temples-and-ngos',
    nav: 'Temples, Trusts & NGOs',
    title: 'Website Design for Temples, Trusts & NGOs | Online Donations | Samverse',
    description: 'WordPress websites for temples, religious trusts and NGOs, with online donations, event calendars, galleries and information for devotees and supporters.',
    eyebrow: 'For temples, trusts & NGOs',
    h1: 'Websites that <span class="grad">connect your community</span>',
    lead: 'Devotees, volunteers and donors look for you online. I build respectful, easy-to-use websites for temples, trusts and NGOs that share your story, events and causes, and make donating simple.',
    wa: 'Hi Sameer, I need a website for our temple / trust / NGO.',
    painTitle: 'What your website can do for you',
    pains: [
      ['Accept donations online', 'Secure donation pages with payment gateways, and donation receipts sent by email.'],
      ['Share events and timings', 'Darshan and aarti timings, festivals, events and announcements that are easy to update.'],
      ['Tell your story', 'History, activities, projects and impact presented beautifully with photos and videos.'],
      ['Reach people everywhere', 'A mobile-friendly site that devotees and supporters can find on Google from anywhere.'],
    ],
    getsTitle: 'What your website includes',
    gets: ['Online donation page', 'Event & festival calendar', 'Timings & announcements', 'History & about pages', 'Photo & video gallery', 'Volunteer sign-up form', 'Location & directions', 'Hindi / multilingual option'],
    projects: ['Our Temples'],
    faqs: [
      ['Can people donate online?', 'Yes. I integrate a payment gateway such as Razorpay so donors can give securely by UPI, card or net banking.'],
      ['Can the website be in Hindi or other languages?', 'Yes. I can build the site in Hindi, English or multiple languages with a language switcher.'],
      ['Can we update timings and events ourselves?', 'Yes. Your team can update timings, events and news from the WordPress dashboard easily.'],
      ['Do you offer special pricing for NGOs?', 'Share your requirements and I\'ll suggest the most cost-effective setup for your organisation.'],
    ],
  },
  {
    type: 'industry',
    slug: 'hotel-website-design',
    nav: 'Hotels & Homestays',
    title: 'Hotel, Resort & Homestay Website Design | Direct Bookings | Samverse',
    description: 'WordPress websites for hotels, resorts, homestays and travel businesses, with room pages, booking enquiries, galleries and local SEO to win direct bookings.',
    eyebrow: 'For hotels, resorts, homestays & travel',
    h1: 'Hotel websites that <span class="grad">win direct bookings</span>',
    lead: 'Every booking through an OTA costs you commission. A great website of your own helps guests book directly. I build stunning, fast hotel and homestay websites that showcase your property and bring in bookings.',
    wa: 'Hi Sameer, I need a website for my hotel / homestay.',
    painTitle: 'What your hotel website should do',
    pains: [
      ['Earn more direct bookings', 'Booking enquiry forms, WhatsApp booking or a booking engine, so guests book with you and not an OTA.'],
      ['Make guests fall in love', 'Large photo galleries, room tours and experiences that sell your property.'],
      ['Found by travellers', 'SEO for "hotels in {place}" and "homestay in {place}" searches, plus Google Maps.'],
      ['Share everything guests need', 'Rooms, rates, amenities, policies, directions and nearby attractions in one place.'],
    ],
    getsTitle: 'What your hotel website includes',
    gets: ['Room & suite pages', 'Booking enquiry / booking engine', 'WhatsApp booking button', 'Photo & video galleries', 'Amenities & policies', 'Nearby attractions guide', 'Guest reviews section', 'Travel SEO setup'],
    projects: ['Our Temples', 'Vansh Group', 'CNN Food & Spices'],
    faqs: [
      ['Can guests book rooms on the website?', 'Yes. I can add a booking enquiry form, WhatsApp booking, or integrate a booking engine or channel manager you already use.'],
      ['Can I update room rates and availability?', 'Yes. Rooms, rates and offers are managed from the dashboard, and a booking plugin can manage availability.'],
      ['Will the site work with my Google Business listing?', 'Yes. I link your website with your Google Business Profile and set up local SEO so travellers find you.'],
      ['How long does it take?', 'Usually 1–3 weeks depending on the number of rooms, pages and booking features.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-lawyers-and-consultants',
    nav: 'Lawyers, CAs & Consultants',
    title: 'Website Design for Lawyers, CAs & Consultants | Samverse',
    description: 'Professional WordPress websites for lawyers, law firms, chartered accountants and consultants that build credibility and bring in client consultations.',
    eyebrow: 'For lawyers, CAs & consultants',
    h1: 'Professional websites that <span class="grad">earn client trust</span>',
    lead: 'Clients choose professionals they trust. I build clean, credible websites for lawyers, chartered accountants and consultants that present your expertise clearly and turn visitors into consultation requests.',
    wa: 'Hi Sameer, I need a website for my practice / firm.',
    painTitle: 'What your professional website should do',
    pains: [
      ['Establish credibility', 'Your qualifications, experience, practice areas and team presented with a polished, professional look.'],
      ['Explain your services', 'Clear pages for each practice area or service, so clients know exactly how you can help.'],
      ['Book consultations', 'Consultation request forms, one-tap call and WhatsApp, available on every page.'],
      ['Show up in search', 'SEO for searches like "GST consultant in {city}" or "property lawyer near me".'],
    ],
    getsTitle: 'What your website includes',
    gets: ['Profile & qualifications', 'Practice area / service pages', 'Consultation request form', 'Team profiles', 'Articles & insights blog', 'Client testimonials', 'Office location & map', 'Local SEO setup'],
    projects: ['Dr. Sudhir Arora', 'Vansh Group', 'Third Eye Social'],
    faqs: [
      ['Can clients book a consultation online?', 'Yes. I add consultation request forms, and can integrate calendar booking tools if you use them.'],
      ['Can I publish articles or legal updates?', 'Yes. A blog section lets you publish articles and updates, which also helps your Google ranking.'],
      ['Is the website suitable for professional guidelines?', 'I keep the design and wording professional and informative. You review and approve all content before launch.'],
      ['How long does it take?', 'Usually 1–2 weeks once your content and profile details are ready.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-startups',
    nav: 'Startups',
    title: 'Startup Website Development on WordPress | Launch Fast | Samverse',
    description: 'Launch your startup website fast on WordPress: modern design, landing pages, product pages, blog and analytics, built to grow with you and easy for your team to edit.',
    eyebrow: 'For startups & new businesses',
    h1: 'Launch your startup with a <span class="grad">website that converts</span>',
    lead: 'You need a sharp, credible website quickly without burning your runway. I build modern startup websites on WordPress that your team can edit, that load fast and that turn visitors into sign-ups and demo requests.',
    wa: 'Hi Sameer, I need a website for my startup.',
    painTitle: 'Why startups build with me',
    pains: [
      ['Launch fast', 'Go from brief to live website quickly, so you can start marketing and fundraising.'],
      ['Built to convert', 'Clear messaging, strong calls to action and landing pages for every campaign.'],
      ['Your team can edit it', 'Marketing can update pages, publish blogs and launch landing pages without a developer.'],
      ['Ready to grow', 'Analytics, SEO foundations and integrations with your CRM and email tools.'],
    ],
    getsTitle: 'What your startup website includes',
    gets: ['Modern homepage & product pages', 'Pricing & features pages', 'Demo / sign-up forms', 'Campaign landing pages', 'Blog for content marketing', 'Analytics & event tracking', 'CRM & email integrations', 'Speed & SEO optimization'],
    projects: ['Third Eye Social', 'Streak Creative', 'India Automation Hub'],
    faqs: [
      ['Why WordPress for a startup?', 'It\'s fast to build, cheap to run, easy for non-developers to edit, and it has integrations for almost every marketing tool.'],
      ['Can you connect forms to our CRM?', 'Yes. I can connect forms to HubSpot, Zoho, Mailchimp, Google Sheets and many others.'],
      ['Can you work from our Figma designs?', 'Yes. I convert Figma designs into pixel-accurate WordPress pages, or design from your brand guidelines.'],
      ['Can you support us after launch?', 'Yes. I offer ongoing support for new pages, landing pages and updates as you grow.'],
    ],
  },
  {
    type: 'industry',
    slug: 'website-for-solar-and-power-companies',
    nav: 'Solar & Power Companies',
    title: 'Website Design for Solar, Power & Electrical Companies | Samverse',
    description: 'WordPress websites for solar installers, power solution providers and electrical companies, with product and service pages, project galleries and quote request forms.',
    eyebrow: 'For solar, power & electrical businesses',
    h1: 'Websites that bring <span class="grad">solar & power enquiries</span>',
    lead: 'Homeowners and businesses compare solar and power companies online before asking for a quote. I build professional websites that explain your solutions, show completed projects and turn visitors into quote requests.',
    wa: 'Hi Sameer, I need a website for my solar / power company.',
    painTitle: 'What your website should do',
    pains: [
      ['Explain your solutions simply', 'Clear pages for solar, inverters, batteries, gensets or electrical services, written for customers, not engineers.'],
      ['Capture quote requests', 'Quote forms asking for monthly bill, location and property type, so you can follow up fast.'],
      ['Prove your experience', 'Project galleries, capacity installed, certifications and client logos that build confidence.'],
      ['Rank for local searches', 'SEO for "solar installation in {city}" and similar high-intent searches.'],
    ],
    getsTitle: 'What your website includes',
    gets: ['Products & solutions pages', 'Quote request form', 'Savings / subsidy information', 'Completed projects gallery', 'Certifications & partners', 'Service area pages', 'WhatsApp enquiry button', 'Local SEO setup'],
    projects: ['Sahni Power Solutions', 'India Automation Hub'],
    faqs: [
      ['Can the quote form ask for details like monthly bill?', 'Yes. Forms can collect monthly electricity bill, location, roof type and more, and email it to you instantly.'],
      ['Can I show government subsidy information?', 'Yes. I can add pages explaining subsidy schemes and the process for customers.'],
      ['Can I add new projects myself?', 'Yes. Add completed projects with photos and details from the dashboard anytime.'],
      ['How long does it take?', 'Usually 1–3 weeks depending on the number of products and pages.'],
    ],
  },

  // ===================== SERVICES =====================
  {
    type: 'service',
    slug: 'wordpress-website-development',
    nav: 'WordPress Website Development',
    title: 'WordPress Website Development Services in India | Samverse',
    description: 'Custom WordPress website development: business websites, portfolios, catalogues and portals that are fast, mobile-friendly, SEO-ready and easy for you to update.',
    eyebrow: 'WordPress website development',
    h1: 'WordPress websites, <span class="grad">built properly</span>',
    lead: 'Your website should look professional, load fast, show up on Google and make it easy for customers to contact you. I build WordPress websites that do all four, and that you can update yourself after launch.',
    wa: 'Hi Sameer, I need a new WordPress website.',
    painTitle: 'What you get with a Samverse website',
    pains: [
      ['Designed around your customers', 'Pages planned around what your visitors need to see and do, with clear calls to action on every page.'],
      ['Fast and mobile-first', 'Lightweight builds, optimized images and caching, tested on real phones before launch.'],
      ['SEO-ready from day one', 'Clean structure, titles and descriptions, schema markup, sitemap and Search Console set up.'],
      ['Yours to manage', 'Built on WordPress with Elementor, so you can edit text, images and pages without code, and you own everything.'],
    ],
    getsTitle: 'Every website includes',
    gets: ['Custom design for your brand', 'Mobile-responsive layout', 'Contact forms & WhatsApp button', 'Speed optimization', 'On-page SEO & schema', 'Google Analytics & Search Console', 'Security basics & backups', 'Training & post-launch support'],
    projects: ['Vansh Group', 'Third Eye Social', 'Sahni Power Solutions', 'Dr. Sudhir Arora'],
    faqs: [
      ['What kinds of WordPress websites do you build?', 'Business and corporate websites, personal brand sites, B2B catalogues, directories and portals, blogs and magazines, and WooCommerce online stores.'],
      ['Do you use templates or custom designs?', 'Either. I can adapt a quality theme for speed and budget, or build a fully custom design from Figma or your references.'],
      ['Will I be able to update the website myself?', 'Yes. I build with Elementor or the block editor and show you how to edit pages, so everyday changes don\'t need a developer.'],
      ['What do you need from me to start?', 'Your logo, the pages you need, content and photos (or a plan for them), and 2–3 websites you like. Then I send a fixed quote and timeline.'],
    ],
  },
  {
    type: 'service',
    slug: 'hire-wordpress-developer',
    nav: 'Hire a WordPress Developer',
    title: 'Hire a Freelance WordPress Developer in India | Samverse',
    description: 'Hire an experienced freelance WordPress developer for projects, monthly support or white-label agency work. Fixed quotes, direct communication, fast turnaround.',
    eyebrow: 'Hire a WordPress developer',
    h1: 'Hire a WordPress developer <span class="grad">you can rely on</span>',
    lead: 'Need a new site, a fix, or an extra pair of hands for your agency? Work directly with me, an experienced freelance WordPress developer, with clear quotes, quick communication and work delivered on time.',
    wa: 'Hi Sameer, I want to hire you for WordPress work.',
    painTitle: 'Why clients hire me',
    pains: [
      ['Direct communication', 'You talk to the person doing the work on WhatsApp, email or calls, with no account managers in between.'],
      ['Clear, fixed quotes', 'Scope and price agreed before work starts, so there are no surprises on the invoice.'],
      ['Experienced since 2020', 'WordPress, Elementor, WooCommerce, speed and SEO across agencies, manufacturers, healthcare and more.'],
      ['Support after launch', 'I stay available for changes, fixes and ongoing maintenance.'],
    ],
    getsTitle: 'Ways to work with me',
    gets: ['Fixed-price website projects', 'Redesigns & migrations', 'Monthly maintenance plans', 'White-label work for agencies', 'Speed & SEO fixes', 'WooCommerce stores', 'Elementor & Figma builds', 'Urgent bug fixes'],
    projects: ['Third Eye Social', 'Streak Creative', 'India Automation Hub', 'Our Temples'],
    faqs: [
      ['How do I get started?', 'Send your requirements on WhatsApp or through the form. I reply with questions if needed, then a fixed quote and timeline, usually within 24 hours.'],
      ['Do you work with clients outside India?', 'Yes. I work with clients and agencies in other countries over WhatsApp, email and video calls.'],
      ['What are your payment terms?', 'Projects usually start with an advance, with the balance before launch. Monthly plans are billed monthly.'],
      ['Can you join an ongoing project?', 'Yes. I can take over or support existing WordPress sites after a quick review of the setup.'],
    ],
  },
  {
    type: 'service',
    slug: 'website-redesign',
    nav: 'Website Redesign',
    title: 'Website Redesign Services | Modern WordPress Redesign | Samverse',
    description: 'Outdated, slow or not mobile-friendly? Get your website redesigned on WordPress with a modern look, faster speed and better SEO, without losing your Google rankings.',
    eyebrow: 'Website redesign',
    h1: 'Give your old website a <span class="grad">modern makeover</span>',
    lead: 'An outdated website quietly costs you customers. I redesign websites on WordPress with a fresh, modern look, faster loading and a mobile-first layout, while protecting the Google rankings you already have.',
    wa: 'Hi Sameer, I want to redesign my website.',
    painTitle: 'Signs it\'s time for a redesign',
    pains: [
      ['It looks outdated', 'Visitors judge your business by your website. A dated design makes a great business look small.'],
      ['It\'s hard to use on phones', 'Most visitors are on mobile. If they have to pinch and zoom, they leave.'],
      ['It\'s slow', 'Every extra second of loading loses visitors and hurts your Google ranking.'],
      ['You can\'t update it', 'If every small change needs a developer, WordPress with Elementor puts you back in control.'],
    ],
    getsTitle: 'What a redesign includes',
    gets: ['Modern, on-brand design', 'Mobile-first responsive layout', 'Speed optimization', 'SEO-safe migration & redirects', 'Content restructuring', 'Clear calls to action', 'Easy editing with Elementor', 'Analytics setup'],
    projects: ['Vansh Group', 'Dr. Sudhir Arora', 'Sahni Power Solutions', 'Our Temples'],
    faqs: [
      ['Will I lose my Google rankings?', 'Not if it\'s done properly. I keep important URLs, set up 301 redirects for changed pages and preserve your SEO settings.'],
      ['Can you redesign a site that isn\'t on WordPress?', 'Yes. I can move your site from Wix, HTML, Joomla or another platform onto WordPress as part of the redesign.'],
      ['Will my website go offline during the redesign?', 'No. I build the new design on a staging site and switch over only when you approve it.'],
      ['Can I keep my existing content?', 'Yes. I can reuse and improve your existing content, images and pages.'],
    ],
  },
  {
    type: 'service',
    slug: 'wordpress-speed-optimization',
    nav: 'Speed Optimization',
    title: 'WordPress Speed Optimization Service | Core Web Vitals | Samverse',
    description: 'Slow WordPress site? I improve loading speed and Core Web Vitals with caching, image optimization, code cleanup and hosting tuning, for better rankings and more conversions.',
    eyebrow: 'WordPress speed optimization',
    h1: 'Make your WordPress site <span class="grad">load fast</span>',
    lead: 'Slow websites lose visitors, sales and Google rankings. I find what\'s slowing your WordPress site down and fix it with caching, image optimization, cleanup and Core Web Vitals improvements.',
    wa: 'Hi Sameer, my WordPress website is slow. Can you help?',
    painTitle: 'Why speed matters',
    pains: [
      ['Visitors don\'t wait', 'Most people leave a page that takes more than a few seconds to load, especially on mobile.'],
      ['Google ranks fast sites higher', 'Core Web Vitals are a ranking factor, so a faster site can rank better.'],
      ['Faster sites convert better', 'Quicker pages mean more enquiries, sign-ups and sales from the same traffic.'],
      ['Lower bounce, better ads', 'Faster landing pages improve ad quality scores and reduce wasted ad spend.'],
    ],
    getsTitle: 'What speed optimization includes',
    gets: ['Before & after speed report', 'Caching setup (LiteSpeed / WP Rocket)', 'Image compression & WebP', 'Lazy loading', 'CSS & JS minification', 'Plugin audit & cleanup', 'Database optimization', 'Core Web Vitals fixes'],
    projects: ['India Automation Hub', 'Third Eye Social', 'Sahni Power Solutions'],
    faqs: [
      ['How much faster will my site get?', 'It depends on your hosting, theme and plugins. I share a before-and-after report from PageSpeed Insights so you can see the improvement.'],
      ['Will optimization break my website?', 'I work carefully, take a full backup first and test every page after each change.'],
      ['Do I need to change my hosting?', 'Not always. I optimize what you have first, and recommend a hosting upgrade only if it is really the bottleneck.'],
      ['How long does it take?', 'Most sites are optimized within 2–4 working days.'],
    ],
  },
  {
    type: 'service',
    slug: 'wordpress-maintenance',
    nav: 'Website Maintenance',
    title: 'WordPress Website Maintenance & Support Plans | Samverse',
    description: 'Monthly WordPress maintenance: updates, backups, security monitoring, uptime checks and small content changes, so your website stays fast, secure and online.',
    eyebrow: 'WordPress maintenance & support',
    h1: 'Your website, <span class="grad">looked after every month</span>',
    lead: 'Outdated plugins, missed backups and security holes are how websites break or get hacked. My maintenance plans keep your WordPress site updated, backed up, secure and running smoothly, so you can focus on your business.',
    wa: 'Hi Sameer, I\'m interested in a WordPress maintenance plan.',
    painTitle: 'Why maintenance matters',
    pains: [
      ['Prevent hacks', 'Most hacked WordPress sites were running outdated plugins or themes. Regular updates close those holes.'],
      ['Never lose your site', 'Regular off-site backups mean your website can be restored quickly if anything goes wrong.'],
      ['Stay fast and online', 'Uptime monitoring and performance checks catch problems before your customers do.'],
      ['Help when you need it', 'Small content changes and fixes handled quickly by someone who knows your site.'],
    ],
    getsTitle: 'What your maintenance plan includes',
    gets: ['WordPress, theme & plugin updates', 'Regular off-site backups', 'Security scans & monitoring', 'Uptime monitoring', 'Speed checks', 'Small content updates', 'Broken link & form checks', 'Monthly report'],
    projects: ['Dr. Sudhir Arora', 'Vansh Group', 'CNN Food & Spices', 'Our Temples'],
    faqs: [
      ['Do you maintain websites you didn\'t build?', 'Yes. I start with a quick health check of your site, fix any urgent issues, and then maintain it monthly.'],
      ['What if my site breaks after an update?', 'Updates are tested and a backup is taken first, so anything that breaks can be fixed or rolled back quickly.'],
      ['Are content changes included?', 'Yes, small changes like text, images and prices are included each month. Bigger work is quoted separately.'],
      ['Can I cancel anytime?', 'Yes. Plans are month to month.'],
    ],
  },
  {
    type: 'service',
    slug: 'elementor-developer',
    nav: 'Elementor Development',
    title: 'Hire an Elementor Developer | Elementor Pro Expert | Samverse',
    description: 'Experienced Elementor and Elementor Pro developer for custom page designs, theme builder templates, WooCommerce layouts and fixes, all pixel-accurate and responsive.',
    eyebrow: 'Elementor development',
    h1: 'Hire an <span class="grad">Elementor expert</span>',
    lead: 'Elementor makes WordPress easy to edit, but building it right takes experience. I build pixel-accurate, responsive Elementor layouts and theme templates that stay fast and easy for you to update.',
    wa: 'Hi Sameer, I need help with an Elementor website.',
    painTitle: 'What I do with Elementor',
    pains: [
      ['Custom page designs', 'Unique, on-brand pages built from your design or references, not generic templates.'],
      ['Theme Builder templates', 'Headers, footers, blog, archive and single-post templates with Elementor Pro.'],
      ['Responsive on every device', 'Every section fine-tuned for desktop, tablet and mobile breakpoints.'],
      ['Fixes & improvements', 'Broken layouts, slow Elementor pages and messy builds cleaned up and optimized.'],
    ],
    getsTitle: 'Elementor services',
    gets: ['Custom page builds', 'Elementor Pro Theme Builder', 'Popups & forms', 'WooCommerce Builder layouts', 'Dynamic content & ACF', 'Global styles & design system', 'Responsive fixes', 'Elementor speed optimization'],
    projects: ['Third Eye Social', 'Streak Creative', 'Vansh Group', 'India Automation Hub'],
    faqs: [
      ['Do you work with Elementor Pro?', 'Yes. I use Elementor Pro features like Theme Builder, dynamic content, popups, forms and WooCommerce Builder.'],
      ['Can you fix my existing Elementor site?', 'Yes. I can fix broken layouts, responsive issues and slow pages on existing Elementor websites.'],
      ['Will I be able to edit the pages myself?', 'Yes. I build with global styles and clean structure so editing text and images is simple.'],
      ['Do you work for agencies?', 'Yes. I often build Elementor sites white-label for agencies.'],
    ],
  },
  {
    type: 'service',
    slug: 'figma-to-wordpress',
    nav: 'Figma to WordPress',
    title: 'Figma to WordPress Conversion | Pixel-Perfect | Samverse',
    description: 'Convert Figma, Adobe XD or PSD designs into pixel-perfect, responsive WordPress websites with Elementor, built fast, clean and easy to edit.',
    eyebrow: 'Figma / XD / PSD to WordPress',
    h1: 'Your design, built <span class="grad">pixel-perfect</span> in WordPress',
    lead: 'You have the design, and you need it live, exactly as designed. I convert Figma, Adobe XD and PSD designs into responsive WordPress websites that match every detail and stay easy to edit.',
    wa: 'Hi Sameer, I have a Figma design to convert to WordPress.',
    painTitle: 'Why designers and agencies use me',
    pains: [
      ['Pixel-accurate builds', 'Spacing, typography, colours and interactions matched closely to your design.'],
      ['Responsive done right', 'Sensible tablet and mobile layouts, even if the design only covers desktop.'],
      ['Easy for clients to edit', 'Built in Elementor or Gutenberg with global styles, so content updates are simple.'],
      ['Fast and clean', 'Optimized images, lean code and good Core Web Vitals scores.'],
    ],
    getsTitle: 'What\'s included',
    gets: ['Figma, XD, PSD & Sketch', 'Elementor or Gutenberg build', 'Responsive tablet & mobile', 'Animations & interactions', 'Forms & integrations', 'Blog & dynamic templates', 'Speed optimization', 'Cross-browser testing'],
    projects: ['Streak Creative', 'Third Eye Social', 'India Automation Hub'],
    faqs: [
      ['What do you need to start?', 'Access to the Figma/XD file (or exported PSDs), fonts, and any content or brand assets.'],
      ['What if my design has no mobile version?', 'I create sensible mobile and tablet layouts based on your desktop design and share them for approval.'],
      ['Which builder do you use?', 'Usually Elementor Pro for easy editing, or Gutenberg blocks if you prefer a lighter setup.'],
      ['Do you work white-label for designers and agencies?', 'Yes. I regularly build designs for agencies and designers under their brand.'],
    ],
  },
  {
    type: 'service',
    slug: 'landing-page-design',
    nav: 'Landing Pages',
    title: 'Landing Page Design for Google & Facebook Ads | Samverse',
    description: 'High-converting landing pages for Google Ads, Meta ads and campaigns. Fast, mobile-first, focused on one goal, with lead forms, WhatsApp and tracking set up.',
    eyebrow: 'Landing page design',
    h1: 'Landing pages that <span class="grad">turn clicks into leads</span>',
    lead: 'Sending ad traffic to a general homepage wastes money. I build fast, focused landing pages for your campaigns, with one clear message, one goal and tracking set up, so more clicks become leads.',
    wa: 'Hi Sameer, I need a landing page for my ads / campaign.',
    painTitle: 'What makes a landing page convert',
    pains: [
      ['One clear goal', 'No distractions, just a strong headline, benefits, proof and one call to action.'],
      ['Loads in a blink', 'Lightweight pages that load fast on mobile, where most ad clicks happen.'],
      ['Tracks every lead', 'Google Analytics, Meta Pixel and conversion tracking set up so you know what works.'],
      ['Easy to test and tweak', 'Duplicate and edit versions quickly to test different offers and headlines.'],
    ],
    getsTitle: 'What your landing page includes',
    gets: ['Conversion-focused layout', 'Lead form + WhatsApp', 'Mobile-first design', 'Fast loading', 'Meta Pixel & GA4 events', 'Google Ads conversion tracking', 'Thank-you page', 'A/B test variations'],
    projects: ['Third Eye Social', 'Streak Creative', 'Sahni Power Solutions'],
    faqs: [
      ['Can the landing page be on my existing website?', 'Yes. I can build it on your current WordPress site, or set up a separate one for campaigns.'],
      ['Will you set up conversion tracking?', 'Yes. I set up GA4 events, Meta Pixel and Google Ads conversion tracking for form submits and WhatsApp clicks.'],
      ['How fast can you deliver?', 'Most landing pages are ready in 3–5 working days once the content and offer are clear.'],
      ['Can you write the page content?', 'I can structure the page and help sharpen your copy for conversions.'],
    ],
  },
  {
    type: 'service',
    slug: 'wordpress-seo-services',
    nav: 'WordPress SEO',
    title: 'WordPress SEO Services | Technical & On-Page SEO | Samverse',
    description: 'Technical and on-page SEO for WordPress: site structure, meta tags, schema markup, sitemaps, speed and Search Console setup, so Google can find and rank your pages.',
    eyebrow: 'WordPress SEO',
    h1: 'Get your WordPress site <span class="grad">ready to rank</span>',
    lead: 'Great content won\'t rank if Google can\'t understand your site. I fix the technical and on-page SEO of WordPress websites, from structure and meta tags to schema, speed and Search Console.',
    wa: 'Hi Sameer, I need SEO help for my WordPress site.',
    painTitle: 'What WordPress SEO fixes',
    pains: [
      ['Pages not indexed', 'Sitemaps, robots and Search Console issues fixed so Google can find your pages.'],
      ['Weak on-page SEO', 'Titles, descriptions, headings and internal links optimized for the searches you want.'],
      ['Missing rich results', 'Schema markup for your business, services, FAQs and products.'],
      ['Slow and not mobile-friendly', 'Speed and mobile usability improved, which both matter for rankings.'],
    ],
    getsTitle: 'What SEO setup includes',
    gets: ['SEO audit report', 'Rank Math / Yoast setup', 'Titles & meta descriptions', 'Heading & URL structure', 'Schema markup', 'XML sitemap & robots.txt', 'Search Console & GA4 setup', 'Internal linking'],
    projects: ['Dr. Sudhir Arora', 'India Automation Hub', 'Sahni Power Solutions'],
    faqs: [
      ['How soon will I see results?', 'Technical fixes take effect as Google recrawls your site, usually over a few weeks. Rankings grow over months with good content.'],
      ['Do you guarantee first-page rankings?', 'No honest SEO can guarantee rankings. I make sure your site is technically sound and optimized to compete.'],
      ['Do you do local SEO?', 'Yes. I optimize for local searches and help set up and link your Google Business Profile.'],
      ['Do you write blog content?', 'I focus on technical and on-page SEO, and can advise on which content to create.'],
    ],
  },
  {
    type: 'service',
    slug: 'wordpress-malware-removal',
    nav: 'Malware Removal & Security',
    title: 'WordPress Malware Removal & Hacked Site Repair | Samverse',
    description: 'Hacked WordPress site? Fast malware removal, cleanup of spam redirects and injected code, Google blacklist removal help and security hardening to stop reinfection.',
    eyebrow: 'Hacked site repair & security',
    h1: 'Hacked WordPress site? <span class="grad">Let\'s fix it fast.</span>',
    lead: 'Spam redirects, strange pages, Google warnings or a site that won\'t load? I clean malware from hacked WordPress sites, remove injected code, and harden security so it doesn\'t happen again.',
    wa: 'Hi Sameer, my WordPress site has been hacked. I need help urgently.',
    painTitle: 'Signs your site is hacked',
    pains: [
      ['Redirects to spam sites', 'Visitors, especially from Google or mobile, get sent to unrelated or harmful websites.'],
      ['Google or browser warnings', '"This site may be hacked" or red warning screens that scare visitors away.'],
      ['Unknown pages or users', 'Spam pages in Google results, new admin users or files you didn\'t create.'],
      ['Site down or very slow', 'Hosting suspended your account, or the site crashes due to malicious scripts.'],
    ],
    getsTitle: 'What the cleanup includes',
    gets: ['Full malware scan', 'Infected file & database cleanup', 'Backdoor removal', 'Spam page & redirect removal', 'Google blacklist review help', 'Password & user reset', 'Security hardening', 'Firewall setup'],
    projects: ['Vansh Group', 'Our Temples', 'CNN Food & Spices'],
    faqs: [
      ['How quickly can you clean my site?', 'I treat hacked sites as urgent. Most cleanups are completed within 24–48 hours of getting access.'],
      ['Will my content be safe?', 'I take a backup first and clean infected files and database entries without deleting your real content.'],
      ['How do I stop it happening again?', 'After cleanup I update everything, remove vulnerable plugins, harden security and set up a firewall. A maintenance plan keeps it protected.'],
      ['What access do you need?', 'WordPress admin and hosting (cPanel or similar) access. Change the passwords after the work is done.'],
    ],
  },
  {
    type: 'service',
    slug: 'wordpress-migration',
    nav: 'Migration & Hosting',
    title: 'WordPress Migration & Hosting Setup | Zero Downtime | Samverse',
    description: 'Move your WordPress site to new hosting or a new domain with zero downtime and no lost SEO. Also Wix, HTML and other platforms migrated to WordPress.',
    eyebrow: 'Website migration & hosting',
    h1: 'Move your website <span class="grad">without the headache</span>',
    lead: 'Changing hosts, domains or platforms can break websites and lose rankings. I migrate WordPress sites safely, and move sites from Wix, HTML and other platforms onto WordPress, with zero downtime and SEO preserved.',
    wa: 'Hi Sameer, I need to migrate my website.',
    painTitle: 'Migrations I handle',
    pains: [
      ['Hosting to hosting', 'Move to faster, better hosting with files, database and email settings transferred correctly.'],
      ['Domain changes', 'Switch to a new domain with 301 redirects so you keep your Google rankings.'],
      ['Other platforms to WordPress', 'Wix, Squarespace, Blogger, Joomla or static HTML moved onto WordPress.'],
      ['HTTPS & DNS setup', 'SSL certificates, DNS records and email records configured properly.'],
    ],
    getsTitle: 'What migration includes',
    gets: ['Full backup before moving', 'Files & database transfer', 'Zero-downtime switch-over', 'DNS & SSL setup', '301 redirects for changed URLs', 'Email & form testing', 'Broken link check', 'Speed check on new host'],
    projects: ['Sahni Power Solutions', 'Dr. Sudhir Arora', 'Vansh Group'],
    faqs: [
      ['Will my website go down during the move?', 'No. I copy and test the site on the new host first, then switch DNS, so visitors see no downtime.'],
      ['Will I lose my Google rankings?', 'Not with proper redirects and settings. I preserve URLs where possible and redirect anything that changes.'],
      ['Can you recommend good hosting?', 'Yes. I can suggest reliable hosting based on your traffic and budget, and set it up for you.'],
      ['Can you move my email too?', 'I make sure your email DNS records keep working, and can help coordinate moving mailboxes if needed.'],
    ],
  },
];

module.exports = PAGES;
