// Case studies for /work/<slug>/ — describe only what is verifiably on each live site.
// `thumb`: optional local screenshot; otherwise a live screenshot is used.
// `related`: landing page slugs from tools/pages-data.js.
module.exports = [
  {
    slug: 'third-eye-social',
    name: 'Third Eye Social',
    url: 'https://thirdeye.social/',
    industry: 'AI Automation Agency',
    thumb: '/assets/work/thirdeye.svg',
    summary: 'A bold, dark-themed website for an AI automation agency that helps businesses deploy AI agents across sales, support, finance, HR and operations.',
    client: 'Third Eye Social builds AI agents that automate repetitive work for mid-size and large businesses in healthcare, finance, insurance, manufacturing, real estate and e-commerce.',
    goals: [
      'Explain a complex offer (AI agents) simply to business decision-makers',
      'Show the range of agent types and industry use cases',
      'Build credibility with case studies and client testimonials',
      'Turn visitors into booked calls',
    ],
    built: [
      'Striking dark design with orange accents and animated headline treatment',
      'Use case sections for each agent type: customer service, sales, finance, HR, legal, marketing and lead generation',
      'Case study cards and client testimonials',
      'FAQ section addressing common concerns about adopting AI',
      'Insights (blog) section for thought leadership',
      '"Book a Call" calls to action throughout, plus WhatsApp',
    ],
    stack: ['WordPress', 'Elementor', 'Hello Elementor theme', 'Yoast SEO'],
    related: ['wordpress-developer-for-agencies', 'website-for-startups', 'elementor-developer'],
  },
  {
    slug: 'vansh-group',
    name: 'Vansh Group',
    url: 'https://vansh.group/',
    industry: 'Electronics Manufacturing (OEM)',
    summary: 'A professional B2B website for an electronics OEM with decades of experience, presenting its product development services, infrastructure and brand partnerships.',
    client: 'Vansh is an electronics original equipment manufacturer offering end-to-end product development and manufacturing from facilities in North India, serving well-known electrical and lighting brands.',
    goals: [
      'Present a wide range of engineering and manufacturing services clearly',
      'Prove capability to large B2B buyers',
      'Make it easy for prospects to enquire about a specific service',
      'Support credibility with a downloadable company profile',
    ],
    built: [
      'Service pages for PCB and circuit development, electrical appliance development, sheet metal, injection moulded parts and tool & die development',
      'Infrastructure and About sections showcasing facilities and experience',
      'Client and brand testimonial carousel',
      'Contact form with a service-type dropdown so enquiries arrive pre-qualified',
      'Company profile download and prominent phone and email calls to action',
      'Insights blog for industry articles',
    ],
    stack: ['WordPress', 'Elementor', 'Arkito theme', 'WooCommerce'],
    related: ['website-for-manufacturers', 'website-redesign', 'wordpress-seo-services'],
  },
  {
    slug: 'india-automation-hub',
    name: 'India Automation Hub',
    url: 'https://indiaautomationhub.com/',
    industry: 'Industrial Automation Media',
    summary: 'A content-rich news and resource portal for India\'s industrial automation community, covering robotics, control systems and Industry 4.0.',
    client: 'India Automation Hub publishes news, special reports, webinars and thought leadership for automation professionals, engineers, plant managers and technology vendors.',
    goals: [
      'Organise a large volume of technical content so readers can find topics quickly',
      'Grow a subscriber base for newsletters and reports',
      'Give vendors and advertisers a credible, professional platform',
    ],
    built: [
      'Magazine-style layout with clear visual hierarchy and thumbnails',
      'Deep category structure: control systems (PLC, DCS, SCADA), robotics, IIoT, OT cybersecurity, sensors and more',
      'Sections for industry roundups, special reports, webinars and leadership moves',
      'Newsletter subscribe form and site-wide search',
      'Recent posts widgets and category filtering',
      'Social integration including LinkedIn and podcast links',
    ],
    stack: ['WordPress', 'Elementor', 'Newsfy theme', 'Yoast SEO'],
    related: ['website-for-manufacturers', 'wordpress-speed-optimization', 'wordpress-seo-services'],
  },
  {
    slug: 'streak-creative',
    name: 'Streak Creative',
    url: 'https://streakcreative.in/',
    industry: 'Growth Marketing Agency',
    thumb: '/assets/work/streakcreative.svg',
    summary: 'A modern, editorial website for a growth marketing agency, built around its proprietary LOOP methodology and industry-specific offers.',
    client: 'Streak Creative builds repeatable growth systems for category leaders in e-commerce, real estate and B2B manufacturing, combining strategy, AI-driven creativity and performance.',
    goals: [
      'Position the agency as a premium, systems-driven partner',
      'Explain the LOOP methodology and services clearly',
      'Capture leads with a blueprint offer and a newsletter',
      'Showcase case studies and industry expertise',
    ],
    built: [
      'Editorial design with serif headlines, bold red accents and 3D imagery',
      'Service navigation for strategy, production and distribution',
      'Dedicated LOOP methodology pages with industry-specific applications',
      'Case studies, About and the Streak Journal blog',
      '"Streak Signals" newsletter sign-up and "Get Your LOOP Growth Blueprint" lead magnet',
      'Clear "Let\'s Talk" calls to action',
    ],
    stack: ['WordPress', 'Elementor', 'Ohio theme', 'Yoast SEO'],
    related: ['wordpress-developer-for-agencies', 'figma-to-wordpress', 'landing-page-design'],
  },
  {
    slug: 'our-temples',
    name: 'Our Temples',
    url: 'https://ourtemples.info/',
    industry: 'Temple Directory & Travel Guide',
    summary: 'A large directory and travel guide of Hindu temples across India and abroad, searchable by state and by deity, with videos, slokas and a blog.',
    client: 'Our Temples helps devotees, pilgrims and travellers discover temples and plan visits, with hundreds of temples catalogued across Indian states and international destinations.',
    goals: [
      'Organise hundreds of temple listings so visitors can browse easily',
      'Let people search by location and by deity',
      'Build a community around videos, slokas and festival guides',
      'Allow temple owners and guests to register',
    ],
    built: [
      'Directory structure with temples by state and by deity (25+ deity categories)',
      'Search and browse by location, deity or state',
      '"Recently added" temples with photos',
      'Videos and slokas/mantras sections',
      'Blog with festival guides and pilgrimage routes',
      'User login and registration for guests and temple owners, and multilingual (Telugu) content',
    ],
    stack: ['WordPress', 'Elementor', 'Golo directory theme', 'Rank Math SEO'],
    related: ['website-for-temples-and-ngos', 'wordpress-seo-services', 'hotel-website-design'],
  },
  {
    slug: 'dr-sudhir-arora',
    name: 'Dr. Sudhir Arora',
    url: 'https://drsudhirarora.com/',
    industry: 'Healthcare & Wellness',
    summary: 'A personal-brand website for an experienced doctor offering mind-body wellness education, online consultations and structured coaching programs.',
    client: 'Dr. Sudhir Arora (MBBS) offers an educational, non-medicinal approach to managing stress, anxiety, anger and negative thinking, mainly for busy professionals and business owners.',
    goals: [
      'Build trust with a clear profile, credentials and experience',
      'Explain each life challenge the programs address',
      'Engage visitors with a free self-assessment',
      'Convert visitors into consultations and course enrolments',
    ],
    built: [
      'Doctor profile with qualifications and registration details',
      'Pages for each life challenge: anxiety, stress, anger, depression, fears, negative thinking and low confidence',
      'Free anxiety self-assessment tool',
      'Online consultation and personal counselling pages',
      'Life coaching program pages with course structure',
      'Blog and contact page',
    ],
    stack: ['WordPress', 'Elementor', 'Hello Elementor theme'],
    related: ['wordpress-website-for-doctors', 'landing-page-design', 'wordpress-seo-services'],
  },
  {
    slug: 'sahni-power-solutions',
    name: 'Sahni Power Solutions',
    url: 'https://sahnipowersolutions.com/',
    industry: 'Generator Rental',
    summary: 'A lead-focused website for a diesel generator rental company, presenting its full fleet from small portable units to large silent gensets.',
    client: 'Sahni Power Solutions rents diesel generators for commercial, industrial, institutional, event and infrastructure needs, on daily, weekly, monthly and annual terms.',
    goals: [
      'Show the full range of generator capacities clearly',
      'Serve very different customers: factories, hospitals, events, construction sites',
      'Generate enquiries and callback requests quickly',
      'Build trust with experience, projects and compliance details',
    ],
    built: [
      'Generator range organised by capacity and type: portable, silent, welding, mobile and industrial',
      'Industry-specific service descriptions for each customer type',
      'Prominent "Enquire Now" and "Request a Call Back" calls to action',
      'Trust indicators: years in business, projects completed and running',
      'Installation photo gallery',
      'Detailed FAQ section and compliance information (CPCB-IV+, noise norms)',
    ],
    stack: ['WordPress', 'Elementor', 'Astra theme', 'Rank Math SEO'],
    related: ['website-for-solar-and-power-companies', 'website-for-manufacturers', 'landing-page-design'],
  },
];
